--------------------------------------------------------
--  File created - niedziela-listopada-27-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "RAILWAY"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"DATE_OF_REGISTRATION" DATE, 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RAILWAY.USERS
SET DEFINE OFF;
Insert into RAILWAY.USERS (USER_ID,NAME,LAST_NAME,EMAIL,ADDRESS,DATE_OF_REGISTRATION,PASSWORD,PHONE_NUMBER) values ('1','Michal','Kowalski','mkowalski@gmail.com','Polna 54 Kraków',to_date('15/03/17','RR/MM/DD'),'qwerty','600-500-400');
Insert into RAILWAY.USERS (USER_ID,NAME,LAST_NAME,EMAIL,ADDRESS,DATE_OF_REGISTRATION,PASSWORD,PHONE_NUMBER) values ('2','Andrzej','Nowak','anowak@gmail.com','Kwiatowa 28 Warszawa',to_date('16/05/16','RR/MM/DD'),'qwerty','300-500-400');
--------------------------------------------------------
--  DDL for Index I_USERID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAILWAY"."I_USERID_PK" ON "RAILWAY"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "RAILWAY"."USERS" ADD CONSTRAINT "I_USERID_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RAILWAY"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "RAILWAY"."USERS" MODIFY ("DATE_OF_REGISTRATION" NOT NULL ENABLE);
  ALTER TABLE "RAILWAY"."USERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "RAILWAY"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "RAILWAY"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "RAILWAY"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
